version: "3.0"

# networks:
#   smart-athletics:
#     external: true

services:
  app:
    build:
      context: .
      dockerfile: docker/Development/php.dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "8081:8081"

  web:
    build:
      context: .
      dockerfile: docker/Development/nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    # networks:
    #   - smart-athletics