version: "3.0"

networks:
  smart-athletics:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: docker/Development/nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - smart-athletics